all:
	gcc main.c
	/home/nicko/work/pin-external-3.31-98869-gfa6f126a8-gcc-linux/pin -t /home/nicko/work/pin-external-3.31-98869-gfa6f126a8-gcc-linux/source/tools/ManualExamples/obj-intel64/pinatrace.so -- ./a.out
	cp noc_trace.out ../
