
SYSTEMC_TARGET_ARCH = linux

SYSTEMC_PATH = YourSystemCReleaseFolder

PKTOOL_PATH = YourPKtoolInstallFolder


SYSTEMC_INC_DIR      = $(SYSTEMC_PATH)/include
SYSTEMC_LIB_DIR      = $(SYSTEMC_PATH)/lib-$(SYSTEMC_TARGET_ARCH)

# new
PKTOOL_INC_DIR       = $(PKTOOL_PATH)/include
PKTOOL_LIB_DIR       = $(PKTOOL_PATH)/lib

# use null version for SystemC-2.1v1 / boost / gcc-3.4.4
# FLAG_WERROR          = -Werror
FLAG_WERROR         =

# Add 'PTHREADS=1' to command line for a pthreads build
ifdef PTHREADS
PFLAGS		     = -DSC_USE_PTHREADS
PLDFLAGS	     = -lpthread
endif

GXX                  = g++
GCC                  = gcc
LD                   = g++

FLAGS                = -g -Wall -pedantic -Wno-long-long $(FLAG_WERROR) \
                       -DSC_INCLUDE_DYNAMIC_PROCESSES $(PFLAGS) \
                       -I$(SYSTEMC_INC_DIR) -I$(PKTOOL_INC_DIR)
LDFLAGS              = -L$(SYSTEMC_LIB_DIR) -lsystemc $(PLDFLAGS)  -L$(PKTOOL_LIB_DIR) -lpktool
#VALGRIND             = valgrind --log-file-exactly=valgrind.log
