all:
	g++ -I/home/nicko/implementations/systemc-2.3.3/include main.cpp  -L/home/nicko/implementations/systemc-2.3.3/lib-linux64  -lsystemc  -fpermissive
view:
	gtkwave waveform.vcd
clean:
	rm a.out  waveform.vcd 

