all:
	g++  -I/home/nicko/implementations/systemc-2.3.3/include -I/home/nicko/work/systemc-ams-2.3.4/include  main.cpp -L/home/nicko/implementations/systemc-2.3.3/lib-linux64 -L/home/nicko/work/systemc-ams-2.3.4/lib-linux64  -lsystemc-ams -lsystemc -lm


